<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="meamr">

  <!-- Parameters -->
  <xacro:property name="base_length" value="0.30" />
  <xacro:property name="base_width"  value="0.30" />
  <xacro:property name="base_height" value="0.08" />

  <xacro:property name="wheel_radius" value="0.03" />
  <xacro:property name="wheel_width"  value="0.02" />
  <xacro:property name="track_width"  value="0.20" />
  <xacro:property name="wheel_zoff"   value="0.03" />

  <xacro:property name="caster_radius" value="0.02" />
  <xacro:property name="caster_width"  value="0.015" />
  <xacro:property name="caster_zoff"   value="0.02" />
  <xacro:property name="caster_xoff"   value="0.12" />

  <xacro:property name="lidar_height" value="0.12" />

  <!-- ðŸ”§ Macros -->
  <xacro:macro name="wheel" params="prefix y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="WheelColor">
          <color rgba="0.1 0.1 0.8 1.0"/>
        </material>
      </visual>
    </link>
    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="0 ${y_reflect * (track_width / 2)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="caster" params="prefix x_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${caster_radius}" length="${caster_width}"/>
        </geometry>
        <material name="CasterColor">
          <color rgba="0.4 0.4 0.4 1.0"/>
        </material>
      </visual>
    </link>
    <joint name="${prefix}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect * caster_xoff} 0 ${-caster_zoff}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Base structure -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${0.5 * base_height}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="ChassisColor">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
  </link>

  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius + wheel_zoff}" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR -->
  <link name="lidar_link">
    <visual>
      <!-- âœ… ä¿®æ­£ï¼šä¸è¦å†æŠ¬é«˜ -->
      <geometry>
        <cylinder radius="0.035" length="0.02"/>
      </geometry>
      <material name="LidarColor">
        <color rgba="1 0.2 0.2 1.0"/>
      </material>
    </visual>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${lidar_height}" rpy="0 0 0"/>
  </joint>

  <!--  Wheels -->
  <xacro:wheel prefix="left_wheel"  y_reflect=" 1"/>
  <xacro:wheel prefix="right_wheel" y_reflect="-1"/>

  <!--  Casters -->
  <xacro:caster prefix="front_caster" x_reflect=" 1"/>
  <xacro:caster prefix="rear_caster"  x_reflect="-1"/>

</robot>
